### ISSUE TITLE
As a core developer I want bdp-core to be Open Source, to be able to use, learn, extend and redistribute it.

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-timeseries-writer#14]
- [x] create LICENSE directory with GPLv3 in it
- [x] update README
- [x] update source file headers @Piiit 
- [x] README: add sections about how to create a licenses list and license headers with maven 
- [x] Documentation: Add a chapter about how to make a project open-source
- [x] Test
- [x] Make repo public
- [x] Port all changes from the `development` to the `master` branch

**Comment by stefanodavid** [comment]
Yes!!

**Comment by Piiit** [comment]
@idm-suedtirol/ict-automation @stefanodavid Finally, bdp-core is open source now, published under the GPLv3 :-)
